# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taiwan Digital Streaming Co. Open Source Project Mirror Site
# title: 北京外国语大学开源软件镜像站
school: Taiwan Digital Streaming Co.
# school: 北京外国语大学
brand: TWDS Open Source Mirror
keyword: Linux Mirror,Mirror Site,Linux,Opensource
operator: seadog007 & james58899 & Haraguroicha
author: TWDS Mirror Op Group
desc: Placeholder
# operator: 北外信息技术中心
logo: true
meow_404: true
issue_tag: twds
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
base: ""
url: "https://mirror.twds.com.tw"
hostname: "mirror.twds.com.tw"
urlv4: "https://mirror4.twds.com.tw"
urlv6: "https://mirror6.twds.com.tw"
aosp: "aosp.mirror.twds.com.tw"
arch_archive: "arch-archive.mirror.twds.com.tw"
pypi: "pypi.mirror.twds.com.tw"
homelink: "https://www.twds.com.tw"
hide_navbar: false
hide_download: false
hide_server_status: true

hide_mirrorz: true
mirrorz_desc: 校园网联合镜像站
mirrorz_link: "https://mirrors.cernet.edu.cn/list"
mirrorz_help_link: "https://help.mirrors.cernet.edu.cn/"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

plugins:
    - jekyll-babel
    - jekyll-sitemap
    - jekyll/fontawesome/svg
    - jekyll-minifier

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_desc.py, Dockerfile*, build.sh]

#sponsors:
#    megvii:
#        name: "旷视科技有限公司"
#        link: "https://megvii.com/"
#        short: "旷视"
#        eng: "Megvii Technology Ltd."
#        logo: "megvii-s"
#    huawei:
#        name: "华为技术有限公司"
#        link: "https://huawei.com/"
#        short: "华为"
#        eng: "Huawei Technologies Co., Ltd."
#        logo: "huawei"

#poweredbys:
#    kunpeng: "海思<sup>®</sup> Kunpeng<sup>®</sup> 920 处理器"

# vim: ts=2 sts=2 sw=2 expandtab
